In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('DatosDemograficosT.csv')

In [3]:
# Notemos que sólo se aprecian las primeras y últimas cinco filas del
# DataFrame
print(data)

          Nombre del Pais Codigo de Pais  Tasa de Natalidad  \
0                   Aruba            ABW             10.244
1             Afghanistan            AFG             35.253
2                  Angola            AGO             45.985
3                 Albania            ALB             12.877
4    United Arab Emirates            ARE             11.044
..                    ...            ...                ...
190           Yemen, Rep.            YEM             32.947
191          South Africa            ZAF             20.850
192      Congo, Dem. Rep.            COD             42.394
193                Zambia            ZMB             40.471
194              Zimbabwe            ZWE             35.715

     Usuarios de Internet   Grupo de ingresos
0                    78.9        Ingreso alto
1                     5.9        Ingreso bajo
2                    19.1  Ingreso medio alto
3                    57.2  Ingreso medio alto
4                    88.0        Ingreso alto
..                    ...                 ...
190                  20.0  Ingreso medio bajo
191                  46.5  Ingreso medio alto
192                   2.2        Ingreso bajo
193                  15.4  Ingreso medio bajo
194                  18.5        Ingreso bajo

[195 rows x 5 columns]

In [4]:
data

,Nombre del Pais,Codigo de Pais,Tasa de Natalidad,Usuarios de Internet,Grupo de ingresos
0,Aruba,ABW,10.244,78.9,Ingreso alto
1,Afghanistan,AFG,35.253,5.9,Ingreso bajo
2,Angola,AGO,45.985,19.1,Ingreso medio alto
3,Albania,ALB,12.877,57.2,Ingreso medio alto
4,United Arab Emirates,ARE,11.044,88.0,Ingreso alto
...,...,...,...,...,...
190,"Yemen, Rep.",YEM,32.947,20.0,Ingreso medio bajo
191,South Africa,ZAF,20.850,46.5,Ingreso medio alto
192,"Congo, Dem. Rep.",COD,42.394,2.2,Ingreso bajo
193,Zambia,ZMB,40.471,15.4,Ingreso medio bajo
194,Zimbabwe,ZWE,35.715,18.5,Ingreso bajo

In [5]:
# Esto se debe a la configuración inicial de Python

In [6]:
# Para ca,biar esto, escribamos el siguiente comando:
pd.set_option('display.max_rows', None)

In [8]:
data

,Nombre del Pais,Codigo de Pais,Tasa de Natalidad,Usuarios de Internet,Grupo de ingresos
0,Aruba,ABW,10.244,78.900000,Ingreso alto
1,Afghanistan,AFG,35.253,5.900000,Ingreso bajo
2,Angola,AGO,45.985,19.100000,Ingreso medio alto
3,Albania,ALB,12.877,57.200000,Ingreso medio alto
4,United Arab Emirates,ARE,11.044,88.000000,Ingreso alto
5,Argentina,ARG,17.716,59.900000,Ingreso alto
6,Armenia,ARM,13.308,41.900000,Ingreso medio bajo
7,Antigua and Barbuda,ATG,16.447,63.400000,Ingreso alto
8,Australia,AUS,13.200,83.000000,Ingreso alto
9,Austria,AUT,9.400,80.618800,Ingreso alto
10,Azerbaijan,AZE,18.300,58.700000,Ingreso medio alto
11,Burundi,BDI,44.151,1.300000,Ingreso bajo
12,Belgium,BEL,11.200,82.170200,Ingreso alto
13,Benin,BEN,36.440,4.900000,Ingreso bajo
14,Burkina Faso,BFA,40.551,9.100000,Ingreso bajo
15,Bangladesh,BGD,20.142,6.630000,Ingreso medio bajo
16,Bulgaria,BGR,9.200,53.061500,Ingreso medio alto
17,Bahrain,BHR,15.040,90.000040,Ingreso alto
18,"Bahamas, The",BHS,15.339,72.000000,Ingreso alto
19,Bosnia and Herzegovina,BIH,9.062,57.790000,Ingreso medio alto
20,Belarus,BLR,12.500,54.170000,Ingreso medio alto
21,Belize,BLZ,23.092,33.600000,Ingreso medio alto
22,Bermuda,BMU,10.400,95.300000,Ingreso alto
23,Bolivia,BOL,24.236,36.940000,Ingreso medio bajo
24,Brazil,BRA,14.931,51.040000,Ingreso medio alto
25,Barbados,BRB,12.188,73.000000,Ingreso alto
26,Brunei Darussalam,BRN,16.405,64.500000,Ingreso alto
27,Bhutan,BTN,18.134,29.900000,Ingreso medio bajo
28,Botswana,BWA,25.267,15.000000,Ingreso medio alto
29,Central African Republic,CAF,34.076,3.500000,Ingreso bajo
30,Canada,CAN,10.900,85.800000,Ingreso alto
31,Switzerland,CHE,10.200,86.340000,Ingreso alto
32,Chile,CHL,13.385,66.500000,Ingreso alto
33,China,CHN,12.100,45.800000,Ingreso medio alto
34,Cote d'Ivoire,CIV,37.320,8.400000,Ingreso medio bajo
35,Cameroon,CMR,37.236,6.400000,Ingreso medio bajo
36,"Congo, Rep.",COG,37.011,6.600000,Ingreso medio bajo
37,Colombia,COL,16.076,51.700000,Ingreso medio alto
38,Comoros,COM,34.326,6.500000,Ingreso bajo
39,Cabo Verde,CPV,21.625,37.500000,Ingreso medio bajo
40,Costa Rica,CRI,15.022,45.960000,Ingreso medio alto
41,Cuba,CUB,10.400,27.930000,Ingreso medio alto
42,Cayman Islands,CYM,12.500,74.100000,Ingreso alto
43,Cyprus,CYP,11.436,65.454800,Ingreso alto
44,Czech Republic,CZE,10.200,74.110400,Ingreso alto
45,Germany,DEU,8.500,84.170000,Ingreso alto
46,Djibouti,DJI,25.486,9.500000,Ingreso medio bajo
47,Denmark,DNK,10.000,94.629700,Ingreso alto
48,Dominican Republic,DOM,21.198,45.900000,Ingreso medio alto
49,Algeria,DZA,24.738,16.500000,Ingreso medio alto
50,Ecuador,ECU,21.070,40.353684,Ingreso medio alto
51,"Egypt, Arab Rep.",EGY,28.032,29.400000,Ingreso medio bajo
52,Eritrea,ERI,34.800,0.900000,Ingreso bajo
53,Spain,ESP,9.100,71.635000,Ingreso alto
54,Estonia,EST,10.300,79.400000,Ingreso alto
55,Ethiopia,ETH,32.925,1.900000,Ingreso bajo
56,Finland,FIN,10.700,91.514400,Ingreso alto
57,Fiji,FJI,20.463,37.100000,Ingreso medio alto
58,France,FRA,12.300,81.919800,Ingreso alto
59,"Micronesia, Fed. Sts.",FSM,23.511,27.800000,Ingreso medio bajo
60,Gabon,GAB,30.555,9.200000,Ingreso medio alto
61,United Kingdom,GBR,12.200,89.844100,Ingreso alto
62,Georgia,GEO,13.332,43.300000,Ingreso medio bajo
63,Ghana,GHA,33.131,12.300000,Ingreso medio bajo
64,Guinea,GIN,37.337,1.600000,Ingreso bajo
65,"Gambia, The",GMB,42.525,14.000000,Ingreso bajo
66,Guinea-Bissau,GNB,37.503,3.100000,Ingreso bajo
67,Equatorial Guinea,GNQ,35.362,16.400000,Ingreso alto
68,Greece,GRC,8.500,59.866300,Ingreso alto
69,Grenada,GRD,19.334,35.000000,Ingreso medio alto
70,Greenland,GRL,14.500,65.800000,Ingreso alto
71,Guatemala,GTM,27.465,19.700000,Ingreso medio bajo
72,Guam,GUM,17.389,65.400000,Ingreso alto
73,Guyana,GUY,18.885,35.000000,Ingreso medio bajo
74,"Hong Kong SAR, China",HKG,7.900,74.200000,Ingreso alto
75,Honduras,HND,21.593,17.800000,Ingreso medio bajo
76,Croatia,HRV,9.400,66.747600,Ingreso alto
77,Haiti,HTI,25.345,10.600000,Ingreso bajo
78,Hungary,HUN,9.200,72.643900,Ingreso alto
79,Indonesia,IDN,20.297,14.940000,Ingreso medio bajo
80,India,IND,20.291,15.100000,Ingreso medio bajo
81,Ireland,IRL,15.000,78.247700,Ingreso alto
82,"Iran, Islamic Rep.",IRN,17.900,29.950000,Ingreso medio alto
83,Iraq,IRQ,31.093,9.200000,Ingreso medio alto
84,Iceland,ISL,13.400,96.546800,Ingreso alto
85,Israel,ISR,21.300,70.800000,Ingreso alto
86,Italy,ITA,8.500,58.459300,Ingreso alto
87,Jamaica,JAM,13.540,37.100000,Ingreso medio alto
88,Jordan,JOR,27.046,41.000000,Ingreso medio alto
89,Japan,JPN,8.200,89.710000,Ingreso alto
90,Kazakhstan,KAZ,22.730,54.000000,Ingreso medio alto
91,Kenya,KEN,35.194,39.000000,Ingreso medio bajo
92,Kyrgyz Republic,KGZ,27.200,23.000000,Ingreso medio bajo
93,Cambodia,KHM,24.462,6.800000,Ingreso bajo
94,Kiribati,KIR,29.044,11.500000,Ingreso medio bajo
95,"Korea, Rep.",KOR,8.600,84.770000,Ingreso alto
96,Kuwait,KWT,20.575,75.460000,Ingreso alto
97,Lao PDR,LAO,27.051,12.500000,Ingreso medio bajo
98,Lebanon,LBN,13.426,70.500000,Ingreso medio alto
99,Liberia,LBR,35.521,3.200000,Ingreso bajo
100,Libya,LBY,21.425,16.500000,Ingreso medio alto
101,St. Lucia,LCA,15.430,46.200000,Ingreso medio alto
102,Liechtenstein,LIE,9.200,93.800000,Ingreso alto
103,Sri Lanka,LKA,17.863,21.900000,Ingreso medio bajo
104,Lesotho,LSO,28.738,5.000000,Ingreso medio bajo
105,Lithuania,LTU,10.100,68.452900,Ingreso alto
106,Luxembourg,LUX,11.300,93.776500,Ingreso alto
107,Latvia,LVA,10.200,75.234400,Ingreso alto
108,"Macao SAR, China",MAC,11.256,65.800000,Ingreso alto
109,Morocco,MAR,21.023,56.000000,Ingreso medio bajo
110,Moldova,MDA,12.141,45.000000,Ingreso medio bajo
111,Madagascar,MDG,34.686,3.000000,Ingreso bajo
112,Maldives,MDV,21.447,44.100000,Ingreso medio alto
113,Mexico,MEX,19.104,43.460000,Ingreso medio alto
114,"Macedonia, FYR",MKD,11.222,65.240000,Ingreso medio alto
115,Mali,MLI,44.138,3.500000,Ingreso bajo
116,Malta,MLT,9.500,68.913800,Ingreso alto
117,Myanmar,MMR,18.119,1.600000,Ingreso medio bajo
118,Montenegro,MNE,11.616,60.310000,Ingreso medio alto
119,Mongolia,MNG,24.275,20.000000,Ingreso medio alto
120,Mozambique,MOZ,39.705,5.400000,Ingreso bajo
121,Mauritania,MRT,33.801,6.200000,Ingreso medio bajo
122,Mauritius,MUS,10.900,39.000000,Ingreso medio alto
123,Malawi,MWI,39.459,5.050000,Ingreso bajo
124,Malaysia,MYS,16.805,66.970000,Ingreso medio alto
125,Namibia,NAM,29.937,13.900000,Ingreso medio alto
126,New Caledonia,NCL,17.000,66.000000,Ingreso alto
127,Niger,NER,49.661,1.700000,Ingreso bajo
128,Nigeria,NGA,40.045,38.000000,Ingreso medio bajo
129,Nicaragua,NIC,20.788,15.500000,Ingreso medio bajo
130,Netherlands,NLD,10.200,93.956400,Ingreso alto
131,Norway,NOR,11.600,95.053400,Ingreso alto
132,Nepal,NPL,20.923,13.300000,Ingreso bajo
133,New Zealand,NZL,13.120,82.780000,Ingreso alto
134,Oman,OMN,20.419,66.450000,Ingreso alto
135,Pakistan,PAK,29.582,10.900000,Ingreso medio bajo
136,Panama,PAN,19.680,44.030000,Ingreso medio alto
137,Peru,PER,20.198,39.200000,Ingreso medio alto
138,Philippines,PHL,23.790,37.000000,Ingreso medio bajo
139,Papua New Guinea,PNG,28.899,6.500000,Ingreso medio bajo
140,Poland,POL,9.600,62.849200,Ingreso alto
141,Puerto Rico,PRI,10.800,73.900000,Ingreso alto
142,Portugal,PRT,7.900,62.095600,Ingreso alto
143,Paraguay,PRY,21.588,36.900000,Ingreso medio alto
144,French Polynesia,PYF,16.393,56.800000,Ingreso alto
145,Qatar,QAT,11.940,85.300000,Ingreso alto
146,Romania,ROU,8.800,49.764500,Ingreso medio alto
147,Russian Federation,RUS,13.200,67.970000,Ingreso alto
148,Rwanda,RWA,32.689,9.000000,Ingreso bajo
149,Saudi Arabia,SAU,20.576,60.500000,Ingreso alto
150,Sudan,SDN,33.477,22.700000,Ingreso medio bajo
151,Senegal,SEN,38.533,13.100000,Ingreso medio bajo
152,Singapore,SGP,9.300,81.000000,Ingreso alto
153,Solomon Islands,SLB,30.578,8.000000,Ingreso medio bajo
154,Sierra Leone,SLE,36.729,1.700000,Ingreso bajo
155,El Salvador,SLV,17.476,23.109300,Ingreso medio bajo
156,Somalia,SOM,43.891,1.500000,Ingreso bajo
157,Serbia,SRB,9.200,51.500000,Ingreso medio alto
158,South Sudan,SSD,37.126,14.100000,Ingreso bajo
159,Sao Tome and Principe,STP,34.537,23.000000,Ingreso medio bajo
160,Suriname,SUR,18.455,37.400000,Ingreso medio alto
161,Slovak Republic,SVK,10.100,77.882600,Ingreso alto
162,Slovenia,SVN,10.200,72.675600,Ingreso alto
163,Sweden,SWE,11.800,94.783600,Ingreso alto
164,Swaziland,SWZ,30.093,24.700000,Ingreso medio bajo
165,Seychelles,SYC,18.600,50.400000,Ingreso alto
166,Syrian Arab Republic,SYR,24.043,26.200000,Ingreso medio bajo
167,Chad,TCD,45.745,2.300000,Ingreso bajo
168,Togo,TGO,36.080,4.500000,Ingreso bajo
169,Thailand,THA,11.041,28.940000,Ingreso medio alto
170,Tajikistan,TJK,30.792,16.000000,Ingreso medio bajo
171,Turkmenistan,TKM,21.322,9.600000,Ingreso medio alto
172,Timor-Leste,TLS,35.755,1.100000,Ingreso medio bajo
173,Tonga,TON,25.409,35.000000,Ingreso medio alto
174,Trinidad and Tobago,TTO,14.590,63.800000,Ingreso alto
175,Tunisia,TUN,19.800,43.800000,Ingreso medio alto
176,Turkey,TUR,16.836,46.250000,Ingreso medio alto
177,Tanzania,TZA,39.518,4.400000,Ingreso bajo
178,Uganda,UGA,43.474,16.200000,Ingreso bajo
179,Ukraine,UKR,11.100,41.000000,Ingreso medio bajo
180,Uruguay,URY,14.374,57.690000,Ingreso alto
181,United States,USA,12.500,84.200000,Ingreso alto
182,Uzbekistan,UZB,22.500,38.200000,Ingreso medio bajo
183,St. Vincent and the Grenadines,VCT,16.306,52.000000,Ingreso medio alto
184,"Venezuela, RB",VEN,19.842,54.900000,Ingreso alto
185,Virgin Islands (U.S.),VIR,10.700,45.300000,Ingreso alto
186,Vietnam,VNM,15.537,43.900000,Ingreso medio bajo
187,Vanuatu,VUT,26.739,11.300000,Ingreso medio bajo
188,West Bank and Gaza,PSE,30.394,46.600000,Ingreso medio bajo
189,Samoa,WSM,26.172,15.300000,Ingreso medio bajo
190,"Yemen, Rep.",YEM,32.947,20.000000,Ingreso medio bajo
191,South Africa,ZAF,20.850,46.500000,Ingreso medio alto
192,"Congo, Dem. Rep.",COD,42.394,2.200000,Ingreso bajo
193,Zambia,ZMB,40.471,15.400000,Ingreso medio bajo
194,Zimbabwe,ZWE,35.715,18.500000,Ingreso bajo